# Generated by Django 4.2.13 on 2024-06-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('phoneNumber', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('linkedId', models.IntegerField(blank=True, null=True)),
                ('linkPrecedence', models.CharField(max_length=254)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
